name:                stack-tpls-demo
version:             0.1.0
#synopsis:
#description:
homepage:            https://github.com/matsubara0507/stack-tpls-demo#readme
license:             MIT
author:              MATSUBARA Nobutada
maintainer:          t12307043@gunma-u.ac.jp
copyright:           MATSUBARA Nobutada
category:            Web
description:         Please see the README on GitHub at <https://github.com/matsubara0507/stack-tpls-demo#readme>

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- NoImplicitPrelude

- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiWayIf
- NumericUnderscores
- OverloadedLabels
- OverloadedStrings
- PolyKinds
- RankNTypes
- StandaloneDeriving
- TypeFamilies
- TypeOperators
- TypeSynonymInstances

dependencies:
- base >= 4.7 && < 5
- aeson
- rio >= 0.1.1.0
- extensible >= 0.6
- mix
- mix-plugin-github
- mix-plugin-xdgcache

library:
  source-dirs: src

executables:
  stack-tpls-demo:
    main: Main.hs
    source-dirs: app
    dependencies:
    - stack-tpls-demo
    - githash
    - dotenv

tests:
  stack-tpls-demo-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - stack-tpls-demo
    - tasty
    - tasty-hspec
    other-modules: []
