resolver: lts-16.12
packages:
- '.'
extra-deps:
- extensible-0.8
- membership-0
- github-0.26
- binary-instances-1.0.0.1
- github: matsubara0507/mix.hs
  commit: 36e88c9a9e5122a8718c5616d6a9fdcd5b223846
  subdirs:
  - mix
  - mix-plugin-github

docker:
  repo: matsubara0507/stack-build
  enable: false
